### ISSUE TITLE
PassHUD does not start

### ISSUE THREAD

**Issue by adur1990** [mnussbaum/PassHUD#1]
Hi,

I downloaded the App using the releases page, unzipped it and tried to start it. Unfortunately, it does not start but says

> You can't open the application "PassHUD.app" because it may be damaged or incomplete.

**Comment by mnussbaum** [comment]
Thanks for opening the issue! I just tried downloading it fresh myself and don't get the same error unfortunately. This is also the first macOS app I've tried to distribute so good odds I've messed it up somehow. What OS version are you on?

Perhaps it was incompletely downloaded? Do you get the same m5sum for the downloaded zip file as I do?

```bash
% md5 PassHUD.app.zip
MD5 (PassHUD.app.zip) = de1975eae4580ef3a5ba278504b180db
```

**Comment by mnussbaum** [comment]
Oh one more thought, do you allow application from outside the app store in your security system preferences? The application is unsigned as well, so at least on my High Sierra machine I need to explicitly allow PassHUD to run in security system preferences too.

**Comment by adur1990** [comment]
I'm using Mojave and apps from outside the App Store are allowed, as well. Have you tried to archive the app for distribution or just copied the `.app` from the Xcode build folder? The latter won't work, I guess.

**Comment by mnussbaum** [comment]
Sorry for the delay on this. I've just cut an 0.2.0 release and packaged it as a DMG built from an archive. Please let me know if this works better for you!

**Comment by adur1990** [comment]
The issue is solved, thank you :)
